# Generated by Django 3.1.5 on 2021-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='craeted_at',
        ),
        migrations.AddField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
