# Generated by Django 3.1.5 on 2021-03-15 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20210315_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 16, 31, 2, 445811)),
        ),
    ]
