# Generated by Django 3.1.5 on 2021-03-15 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20210315_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='is_comolete',
            new_name='is_completed',
        ),
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 16, 33, 26, 159498)),
        ),
    ]
